### ISSUE TITLE
Submissions do not work

### ISSUE THREAD

**Issue by adamskrodzki** [Arachnid/sggc#2]
After submiting my sort solution i saw error:

An internal error occurred:
expected string or bytes-like object
See logs for full stacktrace.

**Comment by Arachnid** [comment]
Error reporting definitely needs improvement. You're getting this error because you didn't supply a blockchain address with your submission.

**Comment by ldct** [comment]
@Arachnid I'm getting this:

`local variable 'expected' referenced before assignment`

**Comment by Arachnid** [comment]
Should be fixed now.
